services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: miniouser     # Логин для root-пользователя
      MINIO_ROOT_PASSWORD: miniopassword  # Пароль для root-пользователя
    volumes:
      - ./minio-data:/data       # Локальная папка для хранения данных
    ports:
      - "9000:9000"              # S3 API (для SDK и CLI)
      - "9001:9001"              # Web Console (UI)
    restart: unless-stopped